version: "3"

services:
  webhooks:
    build:
      context: .
      dockerfile: src/compose/webhooks/Dockerfile
    restart: on-failure
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
